# Generated by Django 5.0.2 on 2024-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchased_courses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
