# Generated by Django 5.0.2 on 2024-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_purchased_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purchased_courses',
            field=models.JSONField(),
        ),
    ]
