# Generated by Django 5.0.2 on 2024-02-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="published_date",
            field=models.DateField(null=True),
        ),
    ]
