# Generated by Django 5.0.2 on 2024-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_rating",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_video",
            field=models.FileField(null=True, upload_to="course_videos/"),
        ),
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
