# Generated by Django 5.0.2 on 2024-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_course_rating_course_course_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_rating",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
