# Generated by Django 5.0.2 on 2024-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_rating",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_video",
            field=models.FileField(blank=True, null=True, upload_to="course_videos/"),
        ),
    ]
